# Generated by Django 3.2.19 on 2025-02-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSpeedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cumulative_layout_shift', models.CharField(default='N/A', max_length=50)),
                ('first_contentful_paint', models.CharField(default='N/A', max_length=50)),
                ('timing', models.CharField(default='N/A', max_length=50)),
                ('total_blocking_time', models.CharField(default='N/A', max_length=50)),
                ('speed_index', models.CharField(default='N/A', max_length=50)),
                ('time_to_interactive', models.CharField(default='N/A', max_length=50)),
                ('first_meaningful_paint', models.CharField(default='N/A', max_length=50)),
                ('screenshot', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
