# Generated by Django 5.1.6 on 2025-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('pagespeed', 'PageSpeed Insights'), ('custom_search', 'Google Custom Search'), ('maps_search', 'Google Maps Search'), ('business_search', 'Google My Business Search'), ('website_status', 'Website Availability Check')], max_length=20)),
                ('query', models.TextField()),
                ('response_data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PageSpeedResult',
        ),
    ]
